### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hebrides** [hebrides/TEST#6]
### Description

These are public facing documents

### Tasks

Compose Searchable: 

- [ ] Line and Block style structured Docs for every application feature
- [ ] API / Developer Docs
- [ ] Version History Docs
- [ ] FAQ (Searchable docs, summed from structured docs)
- [ ] Help Section Docs: Pages so users can re-access Onboarding / Walkthroughs / Update Alerts
- [ ] Wiki / User Issues Forum (maybe)

### Notes:

Use CMS separate from the deployed application to autogenerate and update docs that exist on a separate service from the application with semantic versions
https://docusaurus.io
https://docsify.js.org/
https://nicedoc.io
https://dash.readme.com/login
https://www.gitbook.com/
